### PR TITLE
To fix issue#31

### PR DESCRIPTION
**Pull request by athiruban**
I created a properties file for the default English locale only as of now.

Creating a locale for Tamil language is in-progress with a test.

Do we need to refactor the code using the new resource bundle properties file or we can open a separate ticket for that?

Thanks,

### CODE REVIEW

**Comment by rajmahendra** [comment]
:+1:

**Comment by rohitvvv** [comment]
Do we need to refactor the code using the new resource bundle properties file or we can open a separate ticket for that?
Yes. You will have to refactor. As I indicated earlier in the issue description the file that needs modification is https://github.com/jughyd/GitFx/blob/master/src/main/java/io/github/gitfx/GitResourceBundle.java

Move you test to GitFx/src/test/java/ 
The good thing is your test was picked up by surefire and passed :+1: 
as I see in the travis-ci logs "Tests run: 4, Failures: 0, Errors: 0, Skipped: 0"

**Comment by athiruban** [comment]
Thanks @rohitvvv and @rajmahendra. I updated the code and pushed the commits.

Please review and merge. :)

**Comment by rohitvvv** [comment]
That was quick :100: Merging.

**Pull request merged**
