### PR TITLE
Issue #69

### PR DESCRIPTION
**Pull request by SaiUpadhyayula**
Fixed NullPointer Exception when clicked on Cancel button in the FileDialog

### CODE REVIEW

**Review by rohitvvv — CHANGES_REQUESTED** [review]
Please add a unit test.

**Comment by SaiUpadhyayula** [comment]
As the application is using the Native OS File Dialog for the file upload, it seems we cannot test this functionality through TestFX.

Hence I added a unit test for the null check.

Please check.

**Comment by jbuddha** [comment]
can u check the build failures?

**Comment by SaiUpadhyayula** [comment]
I think the build errors are due to the new dependencies in the previous PR below https://github.com/jughyd/GitFx/pull/67#partial-pull-merging

The dependencies are downloaded without any problem and the build is fine on my Local.

Should we change anything in the Travis CI ?

**Comment by jbuddha** [comment]
have u tried clean install

**Comment by rohitvvv** [comment]
It seems travis build is unable to resolve Loggable annotation.
https://travis-ci.org/jughyd/GitFx/builds/198787540

/home/travis/build/jughyd/GitFx/src/main/java/io/github/gitfx/controller/GitFxController.java:54: error: package com.jcabi.aspects does not exist
import com.jcabi.aspects.Loggable;

**Comment by SaiUpadhyayula** [comment]
Yes, the Clean Install is fine on my machine.

**Comment by rohitvvv** [comment]
Merging for now as the build is clean.

**Pull request merged**
